---
- hosts: all
  become: yes
  tasks: 
  - name: install webserver
    apt:
      name: apache2
      state: present
  -  name:  start webserver
     service:
       name: apache2
       state: started

  - name: i want to create a file
    file:
      path: /home/ubuntu/mytestfile
      state: touch

       


