---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: install webserver
    apt:
      name: apache2
      state: present
  -  name:  start webserver
     service:
       name: apache2
       state: started

  - name: i want to create a file
    file:
      path: /home/ubuntu/mytestfile
      state: touch


  - name: copy dynamic file
    template:
        src: myindexfile.j2
        dest: /var/www/html/index.html
    notify: restartwebserver
 

  handlers:
  - name: restartwebserver
    service:  
       name: apache2
       state: restarted
  
       


